# Generated by Django 4.2.5 on 2023-10-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0002_profile_follows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
